name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    container: amouat/network-utils

    services:
      echo-server:
        image: hashicorp/http-echo

    steps:
      - name: Test
        run: |
          echo "etc hosts"
          cat /etc/hosts
          echo

          echo "etc resolv conf"
          cat /etc/resolv.conf

          dig echo-server

          ping echo-server

          curl echo-server:5678

  # build:
  #   runs-on: ubuntu-latest

  #   container:
  #     image: 2785/golang-ci:1.16.5-0.2.0
  #     env:
  #       DOCKER_HOST: http://docker-dind:2375
  #       DOCKER_DRIVER: overlay2

  #   services:
  #     docker-dind:
  #       image: docker:20.10.7-dind
  #       ports:
  #         - 2375:2375

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Test
  #       run: go test -v ./...
